Repository million-views/praas, pull requests merged in 2020-07, with the labels that each got.

#125 test cases for `proxy-server`
  .env.conduit.example
  .gitignore
  crud-server/src/routes.test.js
  proxy-server/README.md
  proxy-server/src/server.js
  proxy-server/src/server.test.js
Labels: test

#126 fix setting of hiddenFormField from request
  proxy-server/src/server.js
Labels: bug

#137 crud-server, test: implement for `PUT` method
  crud-server/src/routes.test.js
Labels: test

#138 proxy-server fail-checks and optimizations
  proxy-server/src/server.test.js
Labels: enhancement

#139 crud-server, test: increase code coverage
  crud-server/src/routes.test.js
  crud-server/src/routes/api/users.js
Labels: enhancement

#142 crud-server, test: create test user via dotEnv file
  .env.conduit-user.example
  .gitignore
  crud-server/src/model.test.js
  crud-server/src/routes.test.js
  proxy-server/README.md
Labels: feature

#144 crud-server, feat: non 2xx response funneling and then some
  crud-server/README.md
  crud-server/src/lib/error.js
  crud-server/src/lib/helpers.js
  crud-server/src/model.test.js
  crud-server/src/models/conduit.js
  crud-server/src/models/index.js
  crud-server/src/routes.test.js
  crud-server/src/routes/api/conduits.js
  crud-server/src/routes/api/index.js
  crud-server/src/routes/api/users.js
  crud-server/src/server.js
Labels: logging

#160 prass-app-ionic, fix:#157 remove IP from UX
  praas-app-ionic/src/components/Conduit/Create/index.tsx
  praas-app-ionic/src/components/Conduit/Form/IPAllowList/AllowlistItem.tsx
  praas-app-ionic/src/components/Conduit/Form/IPAllowList/index.tsx
  praas-app-ionic/src/components/Conduit/Form/IPAllowList/style.scss
  praas-app-ionic/src/components/Conduit/Form/index.tsx
  praas-app-ionic/src/components/Conduit/Form/schema.ts
  praas-app-ionic/src/types/conduit.d.ts
Labels: chore

#159 crud-server, test: refactor tests by code functionality
  backend/crud-server/src/routes.test.js
Labels: refactor

#165 crud-server, test: optimize and increase code coverage
  backend/crud-server/src/model.test.js
  backend/crud-server/src/routes.test.js
Labels: refactor

#169 allowList validation
  backend/.eslintrc
  backend/crud-server/src/model.test.js
  backend/crud-server/src/routes.test.js
  backend/crud-server/src/routes/api/conduits.js
  backend/crud-server/src/routes/auth.js
  backend/lib/fake-ips.js
  backend/lib/helpers.js
  backend/lib/praas.js
  backend/proxy-server/README.md
  backend/proxy-server/src/server.js
  backend/proxy-server/src/server.test.js
  backend/util/loopback-network.sh
Labels: feature
